import type { SeedMotherboard } from './schema';

/*
 * Платы SP5 — реальные модели, характеристики сверены со страницами производителей (сентябрь 2026).
 * Важно для конфигуратора: платы Supermicro H13 ограничены 400 Вт на сокет, поэтому EPYC 9965 (500 Вт)
 * на них не встаёт — движок должен объяснить это пользователю.
 */
export const motherboards: SeedMotherboard[] = [
  {
    vendor: 'Supermicro',
    model: 'H13SSL-N',
    socket: 'SP5',
    formFactor: 'ATX · 12" × 10.1"',
    sockets: 1,
    dimmSlots: 12,
    maxMemoryGb: 3072,
    maxCpuTdpW: 400,
    pcieX16Slots: 3,
    mcioX8Ports: 0,
    features: ['3 × PCIe 5.0 x16 + 2 × PCIe 5.0 x8', '2 × M.2 PCIe 5.0 x4', '2 × 1GbE', 'ASPEED AST2600 BMC', '8 × SATA3'],
    status: 'AVAILABLE',
    isPlaceholder: false,
    sourceUrl: 'https://www.supermicro.com/en/products/motherboard/h13ssl-n',
    sortOrder: 10,
  },
  {
    vendor: 'Supermicro',
    model: 'H13DSH',
    socket: 'SP5',
    formFactor: 'Proprietary · 17" × 11.5"',
    sockets: 2,
    dimmSlots: 24,
    maxMemoryGb: 6144,
    maxCpuTdpW: 400,
    pcieX16Slots: 2,
    mcioX8Ports: 10,
    features: ['2 × PCIe 5.0 x16 (riser)', '10 × MCIO PCIe 5.0 x8', '2 × M.2 PCIe 3.0 x4', 'ASPEED AST2600 BMC'],
    status: 'AVAILABLE',
    isPlaceholder: false,
    sourceUrl: 'https://www.supermicro.com/en/products/motherboard/h13dsh',
    sortOrder: 20,
  },
  {
    vendor: 'GIGABYTE',
    model: 'MZ33-AR1 (rev. 3.x)',
    socket: 'SP5',
    formFactor: 'E-ATX',
    sockets: 1,
    dimmSlots: 24,
    maxMemoryGb: null,
    maxCpuTdpW: 500,
    pcieX16Slots: 4,
    mcioX8Ports: 0,
    features: ['4 × PCIe 5.0 x16', '24 DIMM (2DPC)', '2 × 10GbE (Broadcom BCM57416)'],
    status: 'AVAILABLE',
    isPlaceholder: false,
    sourceUrl: 'https://www.gigabyte.com/us/Enterprise/Server-Motherboard/MZ33-AR1-rev-3x',
    sortOrder: 30,
  },
  {
    vendor: 'ASRock Rack',
    model: 'TURIN2D24G-2L+/500W',
    socket: 'SP5',
    formFactor: 'Proprietary · 16.93" × 13.78"',
    sockets: 2,
    dimmSlots: 24,
    maxMemoryGb: null,
    maxCpuTdpW: 500,
    pcieX16Slots: 0,
    mcioX8Ports: 18,
    features: ['18 × MCIO PCIe 5.0 x8 (12 с CXL 2.0)', 'RDIMM / RDIMM-3DS до 6400 МТ/с', '24 DIMM (1DPC)'],
    status: 'AVAILABLE',
    isPlaceholder: false,
    sourceUrl: null,
    note: [
      'Слотов x16 нет: видеокарты подключаются через кабельные райзеры MCIO (2 × x8 → x16).',
      'No x16 slots: GPUs connect via MCIO cable risers (2 × x8 → x16).',
    ],
    sortOrder: 40,
  },

  // ── SP7: платы ещё не анонсированы, держим места под вендоров ──
  {
    vendor: 'Supermicro',
    model: 'SP7 · 1P (TBA)',
    socket: 'SP7',
    formFactor: 'TBA',
    sockets: 1,
    dimmSlots: 16,
    maxMemoryGb: null,
    maxCpuTdpW: null,
    pcieX16Slots: null,
    mcioX8Ports: null,
    features: [],
    status: 'COMING_SOON',
    availabilityWindow: 'Q4 2026',
    isPlaceholder: true,
    sourceUrl: null,
    note: ['Ожидается в IV квартале 2026 г. Характеристики уточняются.', 'Expected in Q4 2026. Specifications to be announced.'],
    sortOrder: 110,
  },
  {
    vendor: 'GIGABYTE',
    model: 'SP7 · 2P (TBA)',
    socket: 'SP7',
    formFactor: 'TBA',
    sockets: 2,
    dimmSlots: 32,
    maxMemoryGb: null,
    maxCpuTdpW: null,
    pcieX16Slots: null,
    mcioX8Ports: null,
    features: [],
    status: 'COMING_SOON',
    availabilityWindow: 'Q4 2026',
    isPlaceholder: true,
    sourceUrl: null,
    note: ['Ожидается в IV квартале 2026 г. Характеристики уточняются.', 'Expected in Q4 2026. Specifications to be announced.'],
    sortOrder: 120,
  },
  {
    vendor: 'ASRock Rack',
    model: 'SP7 · 1P (TBA)',
    socket: 'SP7',
    formFactor: 'TBA',
    sockets: 1,
    dimmSlots: 16,
    maxMemoryGb: null,
    maxCpuTdpW: null,
    pcieX16Slots: null,
    mcioX8Ports: null,
    features: [],
    status: 'COMING_SOON',
    availabilityWindow: 'Q4 2026',
    isPlaceholder: true,
    sourceUrl: null,
    note: ['Ожидается в IV квартале 2026 г. Характеристики уточняются.', 'Expected in Q4 2026. Specifications to be announced.'],
    sortOrder: 130,
  },
];
